name: memory-leak-detection.yml

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  docker-integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{!contains(github.event.pull_request.labels.*.name, 'Skip docker integration')}}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: Print Latest run_master.log from /logs/
        run: |
          LATEST_LOG_DIR=$(ls -td /logs/*/ | head -n 1)
          if [ -f "${LATEST_LOG_DIR}run_master.log" ]; then
            echo "== BEGIN LOG: ${LATEST_LOG_DIR}run_master.log =="
            cat "${LATEST_LOG_DIR}run_master.log"
            echo "== END LOG =="
          else
            echo "run_master.log not found in ${LATEST_LOG_DIR}"
          fi

      - name: Docker Build
        run: docker build -t jasminegraph .

      - name: Run Integration Tests
        run: |
          chmod +x test-docker.sh
          ./test-docker.sh